FROM selenium/standalone-firefox

RUN mkdir /home/seluser/app
COPY fineschecker/build/libs/fineschecker-1.0.0.jar  /home/seluser/app/bin.jar
# COPY drivers/firefoxdriver_linux_77 /home/seluser/app/firefoxdriver
COPY run.sh /home/seluser/app
# COPY machine-id /etc/machine-id
RUN sudo chown -R seluser /home/seluser/app
WORKDIR /home/seluser/app
CMD ["java", "-jar", "-Dwebdriver.firefox.driver=chromedriver", "-Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2", "bin.jar"]

